# bare min deployment

# anti pod affinity, resources request and limits and hpa are important things that are missing because
# i'm using a 1 node cluster, it doesn't make sense to add these.

apiVersion: apps/v1
kind: Deployment
metadata:
 name: ultra-boost
 labels:
  app: ultra-boost
spec:
 replicas: 3
 template:
  metadata:
   name: ultra-boost
   labels:
    app: ultra-boost
   annotations:
    prometheus.io/scrape: "true"
  spec:
   containers:
   - name: ultra-boost
     image: ultra-boost
     imagePullPolicy: IfNotPresent
     readinessProbe:
      httpGet:
       path: /-/ready
       port: 8080
     livenessProbe:
      httpGet:
       port: 8080
       path: /-/healthy
   restartPolicy: Always
 selector:
  matchLabels:
   app: ultra-boost
