# bare min deployment

apiVersion: apps/v1
kind: Deployment
metadata:
 name: ultra-boost
 labels:
  app: ultra-boost
spec:
 replicas: 3
 template:
  metadata:
   name: ultra-boost
   labels:
    app: ultra-boost
   annotations:
    prometheus.io/scrape: "true"
  spec:
   containers:
   - name: ultra-boost
     image: ultra-boost
     # For testing purposes, Always. Else IfNotPresent. In prod IfNotPresent should be used.
     imagePullPolicy: Always
   restartPolicy: Always
 selector:
  matchLabels:
   app: ultra-boost
