---
kind: pipeline
type: kubernetes
name: default

clone:
  depth: 1

steps:
- name: build
  image: ghcr.io/ogkevin/ci-base:latest
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker buildx create --driver docker-container --name build-"$(date +%s)" --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make ultra-boost

- name: test
  image: ghcr.io/ogkevin/ci-base:latest
  volumes:
  - name: dockersock
    path: /var/run
  - name: shared-tmp
    path: /tmp
  commands:
  - docker buildx create --driver docker-container --name test-"$(date +%s)" --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make unit-tests

- name: push-pr
  image: ghcr.io/ogkevin/ci-base:latest
  environment:
    GHCR_PASSWORD:
      from_secret: github_token
  when:
    event:
    - pull_request
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker buildx create --driver docker-container --name push-pr-"$(date +%s)" --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make push-pr

- name: push-main
  image: ghcr.io/ogkevin/ci-base:latest
  environment:
    GHCR_PASSWORD:
      from_secret: github_token
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker buildx create --driver docker-container --name push-main-"$(date +%s)" --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make push
  - make push-${DRONE_BUILD_NUMBER}

- name: get kube config
  image: ghcr.io/ogkevin/ci-base:latest
  environment:
    DO_TOKEN:
      from_secret: do_token
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request
  volumes:
  - name: kubeconfig
    path: /kubeconfig
  commands:
  - doctl -t ${DO_TOKEN} kubernetes cluster kubeconfig show dev-cluster > /kubeconfig/conf.yml

- name: deploy ultra-boost image
  image: bitnami/kubectl:1.21
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request
  volumes:
  - name: kubeconfig
    path: /kubeconfig
  commands:
  - kubectl --kubeconfig /kubeconfig/conf.yml -n ultra-boost apply -k kustomize
  - kubectl --kubeconfig /kubeconfig/conf.yml -n ultra-boost set image deployment/ultra-boost ultra-boost=ghcr.io/ogkevin/ultra-boost:${DRONE_BUILD_NUMBER} --record

volumes:
- name: dockersock
  host:
    path: /var/run
- name: shared-tmp
  host:
    path: /tmp
- name: kubeconfig
  temp: {}

---
kind: signature
hmac: 1bbaddf18e2e7fc070a13d3f0fc8e13650b92779f6f90afd309d0086045ae02d

...
