---
kind: pipeline
type: kubernetes
name: main

trigger:
  branch:
  - main
  event:
  - push

clone:
  depth: 1

steps:
- name: build test and push
  # combine these steps for better build kit cache
  image: ghcr.io/ogkevin/ci-base:latest
  environment:
    GHCR_PASSWORD:
      from_secret: github_token
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker buildx create --driver docker-container --name b-"$(tr -dc A-Za-z0-9 </dev/urandom | head -c 10)" --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make ultra-boost unit-tests push push-${DRONE_BUILD_NUMBER}

volumes:
- name: dockersock
  host:
    path: /var/run
- name: shared-tmp
  host:
    path: /tmp

---
kind: pipeline
type: kubernetes
name: pr

trigger:
  event:
  - pull_request

steps:
- name: build test and push
  # combine these steps for better build kit cache
  image: ghcr.io/ogkevin/ci-base:latest
  environment:
    GHCR_PASSWORD:
      from_secret: github_token
  volumes:
  - name: dockersock
    path: /var/run
  - name: shared-tmp
    path: /tmp
  commands:
  - docker buildx create --driver docker-container --name b-"$(tr -dc A-Za-z0-9 </dev/urandom | head -c 10)" --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make ultra-boost unit-tests push-pr push-${DRONE_BUILD_NUMBER}

volumes:
- name: dockersock
  host:
    path: /var/run
- name: shared-tmp
  host:
    path: /tmp

---

name: deploy
type: kubernetes
kind: pipeline

trigger:
  event:
    - promote
  target:
    - production

steps:
- name: get kube config
  image: ghcr.io/ogkevin/ci-base:latest
  environment:
    DO_TOKEN:
      from_secret: do_token
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request
  volumes:
  - name: kubeconfig
    path: /kubeconfig
  commands:
  - make kubeconfig

- name: deploy ultra-boost image
  image: bitnami/kubectl:1.21
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request
  volumes:
  - name: kubeconfig
    path: /kubeconfig
  commands:
  - kubectl --kubeconfig /kubeconfig/conf.yml -n ultra-boost apply -k kustomize
  - kubectl --kubeconfig /kubeconfig/conf.yml -n ultra-boost set image deployment/ultra-boost ultra-boost=ghcr.io/ogkevin/ultra-boost:${DRONE_BUILD_PARENT} --record

volumes:
- name: kubeconfig
  temp: {}

---
kind: signature
hmac: 9d964af2ca9ad5994e860f49fe908e080d6806d0223d7ea25cba66643c6f5688

...
