---
kind: pipeline
type: kubernetes
name: default

clone:
  depth: 1

steps:
- name: pr
  image: ghcr.io/ogkevin/ci-base:latest
  volumes:
  - name: dockersock
    path: /var/run
  - name: shared-tmp
    path: /tmp
  when:
    event:
    - pull_request
  commands:
  - docker buildx create --driver docker-container --name b-"$(tr -dc A-Za-z0-9 </dev/urandom | head -c 10)" --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make build unit-tests push-pr

- name: main
  image: ghcr.io/ogkevin/ci-base:latest
  environment:
    GHCR_PASSWORD:
      from_secret: github_token
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker buildx create --driver docker-container --name b-"$(tr -dc A-Za-z0-9 </dev/urandom | head -c 10)" --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make build unit-tests push push-${DRONE_BUILD_NUMBER}

- name: get kube config
  image: ghcr.io/ogkevin/ci-base:latest
  environment:
    DO_TOKEN:
      from_secret: do_token
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request
  volumes:
  - name: kubeconfig
    path: /kubeconfig
  commands:
  - doctl -t ${DO_TOKEN} kubernetes cluster kubeconfig show dev-cluster > /kubeconfig/conf.yml

- name: deploy ultra-boost image
  image: bitnami/kubectl:1.21
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request
  volumes:
  - name: kubeconfig
    path: /kubeconfig
  commands:
  - kubectl --kubeconfig /kubeconfig/conf.yml -n ultra-boost apply -k kustomize
  - kubectl --kubeconfig /kubeconfig/conf.yml -n ultra-boost set image deployment/ultra-boost ultra-boost=ghcr.io/ogkevin/ultra-boost:${DRONE_BUILD_NUMBER} --record

volumes:
- name: dockersock
  host:
    path: /var/run
- name: shared-tmp
  host:
    path: /tmp
- name: kubeconfig
  temp: {}

---
kind: signature
hmac: 392de050d5724e374a7661e904a03265adaf4997e3ce535dfbede55ca46ad3c5

...
