---
kind: pipeline
type: docker
name: builder

clone:
  depth: 1

steps:
- name: build
  image: ghcr.io/ogkevin/ci-base:latest
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker buildx create --driver docker-container --name locall --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make ultra-boost

- name: test
  image: ghcr.io/ogkevin/ci-base:latest
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  - name: shared-tmp
    path: /tmp
  commands:
  - docker buildx create --driver docker-container --name locall --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make unit-tests

- name: push-pr
  image: ghcr.io/ogkevin/ci-base:latest
  environment:
    GHCR_PASSWORD:
      from_secret: github_token
  when:
    event:
    - pull_request
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker buildx create --driver docker-container --name locall --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make push-pr

- name: push-main
  image: ghcr.io/ogkevin/ci-base:latest
  environment:
    GHCR_PASSWORD:
      from_secret: github_token
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker buildx create --driver docker-container --name locall --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make push

- name: push-tag
  image: ghcr.io/ogkevin/ci-base:latest
  environment:
    GHCR_PASSWORD:
      from_secret: github_token
  when:
    event:
    - tag
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker buildx create --driver docker-container --name locall --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
  - make push-${DRONE_SEMVER}

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: shared-tmp
  host:
    path: /tmp
---
kind: signature
hmac: e7a42618f3ed4d177bc2daf91bb4719ecc5f964df81987f26048b9ec40fa0bd9
