apiVersion: v1
kind: Service
metadata:
  name: ultra-boost
spec:
  ports:
  - port: 8080
  selector:
    app: ultra-boost
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ultra-boost
  name: ultra-boost
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ultra-boost
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: ultra-boost
      name: ultra-boost
    spec:
      containers:
      - image: ghcr.io/ogkevin/ultra-boost:None
        imagePullPolicy: Always
        name: ultra-boost
      restartPolicy: Always
